import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                {/* <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css" /> */}
                <title>Admin Dashboard - Growup</title>
            </head>
            <body>
                {/* <ToastContainer /> */}

                {children}
            </body>
            {/* <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script> */}
        </html>
    );
}
